"""fix timestamps defaults

Revision ID: 6a78ee8aaa6d
Revises: e1d9a5cf6e6d
Create Date: 2025-12-16 01:47:40.482622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a78ee8aaa6d'
down_revision: Union[str, Sequence[str], None] = 'e1d9a5cf6e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
